#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

## Saving the unstaged changes
STASH_NAME="pre-commit-$(date +%s)"
git stash save -q --keep-index $STASH_NAME

## Run script file with tests
test_result=1
./Scripts/run_tests.sh
test_result=$?

STASH_NUM=$(git stash list | grep $STASH_NAME | sed -re 's/stash@\{(.*)\}.*/\1/')
if [ -n "$STASH_NUM" ];then
    git stash pop -q stash@{$STASH_NUM}
fi

[ $test_result -ne 0 ] && exit 1

echo "${GREEN}✔ Successful Commit${NC} 🤓 🚀"
exit 0
